### ISSUE TITLE
模型在训练的时候很奇怪

### ISSUE THREAD

**Issue by cxq1** [Luo-Z13/pointobb#1]
![1701699267172](https://github.com/Luo-Z13/pointobb/assets/35260648/9676c00e-3ee4-41e1-925f-69fe0550ffc0)
不知道为什么训练的时长会突然变长，很奇怪

**Comment by Luo-Z13** [comment]
> ![1701699267172](https://private-user-images.githubusercontent.com/35260648/287725400-9676c00e-3ee4-41e1-925f-69fe0550ffc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTk2ODcsIm5iZiI6MTcwMTY5OTM4NywicGF0aCI6Ii8zNTI2MDY0OC8yODc3MjU0MDAtOTY3NmMwMGUtM2VlNC00MWUxLTkyNWYtNjlmZTA1NTBmZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZjUwNGVjYTAzNzI2MjJlY2YzNTM0NGI4MTA3ZjVjNGQ0YjhlYzA0YjI3OTJmMGRiY2U4M2Q0YjAxYzFkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SjQM8xmilwzsDQNQ801ZWDqViVxh5giMSeIeyWdgLA) 不知道为什么训练的时长会突然变长，很奇怪

Hello, this occurs because the angle branch is introduced after the "burn_in_step1" phase (as mentioned in the paper). You can adjust "burn_in_step1" and "burn_in_step2" in the config file.

**Comment by cxq1** [comment]
thanks for your reply. it's a great work!!
How long will it take you to train the model using two Gpus

**Comment by Luo-Z13** [comment]
> thanks for your reply. it's a great work!! How long will it take you to train the model using two Gpus

If you use the default configs, it takes about 15 hours on the DOTA-v1.0 and about 16 hours on DIOR-R.

**Comment by cxq1** [comment]
> > Whether the model training will become inaccurate, when the training is interrupted, retraining re-enters the ""burn-in step 1" phase
> 
> If interrupted, it is recommended to manually set the "iter_count" in the configs to the state at which the training was interrupted. Then, follow the resume procedure provided by MMDetection.

What version of mmcv are you using? Is pytorch the default 1.9? I was curious, why did I train on an A100 GPU for more than 5 days

**Comment by Luo-Z13** [comment]
> > > Whether the model training will become inaccurate, when the training is interrupted, retraining re-enters the ""burn-in step 1" phase
> > 
> > 
> > If interrupted, it is recommended to manually set the "iter_count" in the configs to the state at which the training was interrupted. Then, follow the resume procedure provided by MMDetection.
> 
> What version of mmcv are you using? Is pytorch the default 1.9? I was curious, why did I train on an A100 GPU for more than 5 days

My environment:
- PyTorch: 1.9.0
- CUDA Runtime: 11.1
- CuDNN: 8.0.5
- TorchVision: 0.10.0
- OpenCV: 4.8.1
- MMCV: 1.4.5
- MMDetection: 2.13.0+c820f32
