### ISSUE TITLE
It seems that there is no Dior-R trained model configuration file and corresponding pre-trained model file in MMrotate. How to use mmrotate to get the final result?

### ISSUE THREAD

**Issue by xinyue-sun** [Luo-Z13/pointobb#10]

**Comment by Luo-Z13** [comment]
> _No description provided._

Hi, you can change your mmrotate into 1.x version and you can find configs about DIOR-R, like https://github.com/open-mmlab/mmrotate/blob/1.x/configs/_base_/datasets/dior.py
