### ISSUE TITLE
GPU Configuration

### ISSUE THREAD

**Issue by Zhuzi24** [Luo-Z13/pointobb#14]
I would like to ask about the minimum GPU memory requirements

**Comment by Luo-Z13** [comment]
> I would like to ask about the minimum GPU memory requirements

2 16G V100 GPUs are enough, for other problems with GPU you can see https://github.com/Luo-Z13/pointobb/issues/7.

**Comment by Zhuzi24** [comment]
ok，so what's the minimum  need for a single card?

**Comment by Luo-Z13** [comment]
> ok，so what's the minimum need for a single card?

One 24G GPU is enough for DIOR-R.

**Comment by Zhuzi24** [comment]
o的K
