### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by yaosx425** [Luo-Z13/pointobb#18]
I use my own dataset for training, and the format of the dataset is the same as the format of DOTA. After training 24 epochs, how can I visualize it? I want to test an image

**Comment by Luo-Z13** [comment]
Hello, after completing the inference and obtaining pseudo rbox labels in DOTA format, you can use the `browse_dataset.py` in mmrotate (tools/misc/browse_dataset.py) to visualize the pseudo-labels generated by the PointOBB inference.

**Comment by yaosx425** [comment]
> Hello, after completing the inference and obtaining pseudo rbox labels in DOTA format, you can use the `browse_dataset.py` in mmrotate (tools/misc/browse_dataset.py) to visualize the pseudo-labels generated by the PointOBB inference.

但是我在completing the inference and obtaining pseudo rbox labels in DOTA format的时候，代码报错，显示我缺少一些东西，这是怎么回事？麻烦作者看下我最新问的那个问题，您有遇到过吗？
