### ISSUE TITLE
关于注释文件

### ISSUE THREAD

**Issue by cxq1** [Luo-Z13/pointobb#2]
切分好的dota的数据集，有很多annfiles都是空的，即使转成点注释的 coco 格式的文件，也没有处理，这是否会有影响？
有没有必要在对训练数据集处理的时候 做进一步处理，跳过为空的注释文件？

**Comment by Luo-Z13** [comment]
> 切分好的dota的数据集，有很多annfiles都是空的，即使转成点注释的 coco 格式的文件，也没有处理，这是否会有影响？ 有没有必要在对训练数据集处理的时候 做进一步处理，跳过为空的注释文件？

You may notice that the dataloader setting in the config file: 'filter_empty_gt = True'. Consequently, MMDetection typically filters out this data, and there's no need for further processing. However, you could consider treating them as additional negative samples and utilize them during training if you find it beneficial.

**Comment by cxq1** [comment]
> > 切分好的dota的数据集，有很多annfiles都是空的，即使转成点注释的 coco 格式的文件，也没有处理，这是否会有影响？ 有没有必要在对训练数据集处理的时候 做进一步处理，跳过为空的注释文件？
> 
> You may notice that the dataloader setting in the config file: 'filter_empty_gt = True'. Consequently, MMDetection typically filters out this data, and there's no need for further processing. However, you could consider treating them as additional negative samples and utilize them during training if you find it beneficial.

Thank you for your sincere reply
