### ISSUE TITLE
伪标签训练mmrotate

### ISSUE THREAD

**Issue by g973839433** [Luo-Z13/pointobb#21]
作者您好，在用生成的伪标签训练mmrotate的旋转框算法时，是直接用mmrotate1.x版本，还是将1.x版本中的dior相关的文件迁移到mmrotate0.3.x版本中，我看好像1.x版本用的人不是太多，用起来会不会问题比较多

**Comment by Luo-Z13** [comment]
> 作者您好，在用生成的伪标签训练mmrotate的旋转框算法时，是直接用mmrotate1.x版本，还是将1.x版本中的dior相关的文件迁移到mmrotate0.3.x版本中，我看好像1.x版本用的人不是太多，用起来会不会问题比较多

你好，论文中训练是使用的1.x版本，当然也可以迁移到0.3.x版本中，1.x版本支持的算法更多，具体看你个人的使用习惯。

**Comment by g973839433** [comment]
> > 作者您好，在用生成的伪标签训练mmrotate的旋转框算法时，是直接用mmrotate1.x版本，还是将1.x版本中的dior相关的文件迁移到mmrotate0.3.x版本中，我看好像1.x版本用的人不是太多，用起来会不会问题比较多
> 
> 你好，论文中训练是使用的1.x版本，当然也可以迁移到0.3.x版本中，1.x版本支持的算法更多，具体看你个人的使用习惯。

谢谢回复，能否提供一下在mmrotate上训练oriented RCNN用DIOR数据集的config配置文件呢。
祝好
