### ISSUE TITLE
推理步骤的问题

### ISSUE THREAD

**Issue by g973839433** [Luo-Z13/pointobb#22]
作者您好，我想问一下，在推理阶段得到DOTA与DIOR-R对应的pseudo_obb_result.json后，后面的步骤是转为COCO,再从COCO转为DOTA格式，那pseudo_obb_result.json文件是什么格式的数据呢，DOTA数据集对应的pseudo_obb_result.json不是DOTA格式么，我看后面的步骤也只是针对DIOR-R的，还是说两个数据集得到的pseudo_obb_result.json都要进行后续的处理，github上的步骤只是用DIOR-R举例子。

**Comment by Luo-Z13** [comment]
> 作者您好，我想问一下，在推理阶段得到DOTA与DIOR-R对应的pseudo_obb_result.json后，后面的步骤是转为COCO,再从COCO转为DOTA格式，那pseudo_obb_result.json文件是什么格式的数据呢，DOTA数据集对应的pseudo_obb_result.json不是DOTA格式么，我看后面的步骤也只是针对DIOR-R的，还是说两个数据集得到的pseudo_obb_result.json都要进行后续的处理，github上的步骤只是用DIOR-R举例子。

你好，这里的COCO指的就是".json"文件，实际上转换阶段出现了两次COCO格式（即json文件），所以按步骤执行即可。DOTA格式指的是labelTxt（".txt")文件，DOTA和DIOR-R两个数据集都需要进行相同处理，得到各自的伪标签。
