### ISSUE TITLE
关于全监督训练阶段，在Dior数据集上训练oriented rcnn

### ISSUE THREAD

**Issue by xinyue-sun** [Luo-Z13/pointobb#25]
作者您好，在训练全监督检测器阶段我遇到了一个问题——mmrotate的官方源码中没有注册dior数据集（没有dior.py），模型配置文件也只有oriented_rcnn_r50_fpn_1x_dota_le90.py，而没有oriented_rcnn_r50_fpn_1x_dior_le90.py。我尝试了自己修改，但是训练阶段一直报错KeyError: 'DIORDataset is not in the dataset registry'

**Comment by Luo-Z13** [comment]
> 作者您好，在训练全监督检测器阶段我遇到了一个问题——mmrotate的官方源码中没有注册dior数据集（没有dior.py），模型配置文件也只有oriented_rcnn_r50_fpn_1x_dota_le90.py，而没有oriented_rcnn_r50_fpn_1x_dior_le90.py。我尝试了自己修改，但是训练阶段一直报错KeyError: 'DIORDataset is not in the dataset registry'

你好，需要到mmrotate的数据集定义中模仿dota.py的数据集新注册一个DIORDataset，除类别、图像幅面外，格式和DOTA保持一致就能正常运行，注册完新数据集之后再去修改cfg。
