### ISSUE TITLE
测试可视化失败

### ISSUE THREAD

**Issue by zhu011** [Luo-Z13/pointobb#5]
val=dict(
        samples_per_gpu=2,
        type=dataset_type,
        ann_file = data_root_trainval + "trainval_1024_P2Bfmt_dotav10_rbox.json",
        img_prefix = data_root_trainval + 'images/',
        pipeline=test_pipeline,
        test_mode=False,
    ),
    test=dict(
        type=dataset_type,
        img_prefix=data_root_test + 'testfordebug/',
        ann_file=data_root_test + "testfordebug_rbox_pt_P2Bfmt.json",
        pipeline=test_pipeline))
想请问作者testfordebug_rbox_pt_P2Bfmt.json这个是什么文件
可视化的时候直接用val中的文件可视化失败
python tools/test.py configs2/pointobb/pointobb_r50_fpn_2x_ssdd.py work_dir/epoch_50.pth --show-dir dir
运行指令是这个，数据集已经经过转化，报错为loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
self classes:['ship']
=========0===========
load checkpoint from local path: work_dir/epoch_50.pth
[                                                  ] 0/232, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 203, in main
    args.show_score_thr)
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/apis/test.py", line 25, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/cocofmt_obb.py", line 495, in __getitem__
    data = super(CocoFmtObbDataset, self).__getitem__(idx)
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/custom.py", line 192, in __getitem__
    return self.prepare_test_img(idx)
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/custom.py", line 234, in prepare_test_img
    return self.pipeline(results)
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/loading.py", line 382, in __call__
    results = self._load_bboxes(results)
  File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/loading.py", line 247, in _load_bboxes
    ann_info = results['ann_info']
KeyError: 'ann_info'
 val=dict(
        samples_per_gpu=2,
        type=dataset_type,
        ann_file = data_root_test + "test.json",
        img_prefix = data_root_test + 'images/',
        pipeline=test_pipeline,
        test_mode=False,
    ),
    test=dict(
        type=dataset_type,
        img_prefix=data_root_test + 'images/',
        ann_file=data_root_test + "test.json",
        pipeline=test_pipeline))

**Comment by Luo-Z13** [comment]
> ```
> val=dict(
>     samples_per_gpu=2,
>     type=dataset_type,
>     ann_file = data_root_trainval + "trainval_1024_P2Bfmt_dotav10_rbox.json",
>     img_prefix = data_root_trainval + 'images/',
>     pipeline=test_pipeline,
>     test_mode=False,
> ),
> test=dict(
>     type=dataset_type,
>     img_prefix=data_root_test + 'testfordebug/',
>     ann_file=data_root_test + "testfordebug_rbox_pt_P2Bfmt.json",
>     pipeline=test_pipeline))
> ```
> 
> 想请问作者testfordebug_rbox_pt_P2Bfmt.json这个是什么文件 可视化的时候直接用val中的文件可视化失败 python tools/test.py configs2/pointobb/pointobb_r50_fpn_2x_ssdd.py work_dir/epoch_50.pth --show-dir dir 运行指令是这个，数据集已经经过转化，报错为loading annotations into memory... Done (t=0.00s) creating index... index created! self classes:['ship'] =========0=========== load checkpoint from local path: work_dir/epoch_50.pth [ ] 0/232, elapsed: 0s, ETA:Traceback (most recent call last): File "tools/test.py", line 237, in main() File "tools/test.py", line 203, in main args.show_score_thr) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/apis/test.py", line 25, in single_gpu_test for i, data in enumerate(data_loader): File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise raise self.exc_type(msg) KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/cocofmt_obb.py", line 495, in **getitem** data = super(CocoFmtObbDataset, self).**getitem**(idx) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/custom.py", line 192, in **getitem** return self.prepare_test_img(idx) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/custom.py", line 234, in prepare_test_img return self.pipeline(results) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/compose.py", line 40, in **call** data = t(data) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/loading.py", line 382, in **call** results = self._load_bboxes(results) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/loading.py", line 247, in _load_bboxes ann_info = results['ann_info'] KeyError: 'ann_info' val=dict( samples_per_gpu=2, type=dataset_type, ann_file = data_root_test + "test.json", img_prefix = data_root_test + 'images/', pipeline=test_pipeline, test_mode=False, ), test=dict( type=dataset_type, img_prefix=data_root_test + 'images/', ann_file=data_root_test + "test.json", pipeline=test_pipeline))

Hello, the function of pointobb is to transform the single-point annotation into RBox pseudo annotation **in the training set**; therefore, the annotation of the test set cannot be obtained. The file `testfordebug_rbox_pt_P2Bfmt.json` need not be considered. If visualization is desired, please replace the test set path with the training set path. Should you have any additional queries, feel free to inquire at any time.

**Comment by yaosx425** [comment]
> ```
> val=dict(
>     samples_per_gpu=2,
>     type=dataset_type,
>     ann_file = data_root_trainval + "trainval_1024_P2Bfmt_dotav10_rbox.json",
>     img_prefix = data_root_trainval + 'images/',
>     pipeline=test_pipeline,
>     test_mode=False,
> ),
> test=dict(
>     type=dataset_type,
>     img_prefix=data_root_test + 'testfordebug/',
>     ann_file=data_root_test + "testfordebug_rbox_pt_P2Bfmt.json",
>     pipeline=test_pipeline))
> ```
> 
> 想请问作者testfordebug_rbox_pt_P2Bfmt.json这个是什么文件 可视化的时候直接用val中的文件可视化失败 python tools/test.py configs2/pointobb/pointobb_r50_fpn_2x_ssdd.py work_dir/epoch_50.pth --show-dir dir 运行指令是这个，数据集已经经过转化，报错为loading annotations into memory... Done (t=0.00s) creating index... index created! self classes:['ship'] =========0=========== load checkpoint from local path: work_dir/epoch_50.pth [ ] 0/232, elapsed: 0s, ETA:Traceback (most recent call last): File "tools/test.py", line 237, in main() File "tools/test.py", line 203, in main args.show_score_thr) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/apis/test.py", line 25, in single_gpu_test for i, data in enumerate(data_loader): File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise raise self.exc_type(msg) KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/cocofmt_obb.py", line 495, in **getitem** data = super(CocoFmtObbDataset, self).**getitem**(idx) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/custom.py", line 192, in **getitem** return self.prepare_test_img(idx) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/custom.py", line 234, in prepare_test_img return self.pipeline(results) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/compose.py", line 40, in **call** data = t(data) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/loading.py", line 382, in **call** results = self._load_bboxes(results) File "/root/autodl-tmp/pointobb/PointOBB/mmdet/datasets/pipelines/loading.py", line 247, in _load_bboxes ann_info = results['ann_info'] KeyError: 'ann_info' val=dict( samples_per_gpu=2, type=dataset_type, ann_file = data_root_test + "test.json", img_prefix = data_root_test + 'images/', pipeline=test_pipeline, test_mode=False, ), test=dict( type=dataset_type, img_prefix=data_root_test + 'images/', ann_file=data_root_test + "test.json", pipeline=test_pipeline))

想问下同学 成功了吗？ 我报这个错误
call last):
  File "tools/test.py", line 240, in <module>
    main()
  File "tools/test.py", line 206, in main
    args.show_score_thr)
  File "/data2/shuxuan/PointOBB/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/data2/shuxuan_anaconda/envs/openmmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/shuxuan_anaconda/envs/openmmlab1/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "/data2/shuxuan_anaconda/envs/openmmlab1/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data2/shuxuan_anaconda/envs/openmmlab1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/shuxuan_anaconda/envs/openmmlab1/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/data2/shuxuan/PointOBB/mmdet/models/detectors/base.py", line 177, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/data2/shuxuan/PointOBB/mmdet/models/detectors/base.py", line 150, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
TypeError: simple_test() missing 4 required positional arguments: 'gt_bboxes', 'gt_anns_id', 'gt_true_bboxes', and 'gt_labels'
