### ISSUE TITLE
DOTA数据集图像可以用png格式吗

### ISSUE THREAD

**Issue by xinyue-sun** [Luo-Z13/pointobb#9]
请教一下DOTA数据集图像可以用png格式吗？我用的图像是png格式，但是报错FileNotFoundError: [Errno 2] No such file or directory: '/data/lxy1/mmrotate-main/mmrotate-main/data/split_ss_dota_1024_200/trainval/images/P1078__1024__824___824.jpg'。似乎程序自动加载了jpg图像，我应该怎么修改？

**Comment by xinyue-sun** [comment]
Can DOTA data set images be in png format? The image I used is png format, but I got an error：
”FileNotFoundError: [Errno 2] No such file or directory: '/data/lxy1/mmrotate-main/mmrotate-main/data/split_ss_dota_1024_200/trainval/images/P1078__1024__824___824.jpg'“
It seems that the program automatically loaded the jpg image, how should I modify it？

**Comment by Luo-Z13** [comment]
> 请教一下DOTA数据集图像可以用png格式吗？我用的图像是png格式，但是报错FileNotFoundError: [Errno 2] No such file or directory: '/data/lxy1/mmrotate-main/mmrotate-main/data/split_ss_dota_1024_200/trainval/images/P1078__1024__824___824.jpg'。似乎程序自动加载了jpg图像，我应该怎么修改？

可以的，在test_dota2coco_P2B_obb-pt.py中把# DOTA 后缀的取消注释(png)，# DIOR 后缀进行注释(jpg)即可， 如这一行 https://github.com/Luo-Z13/pointobb/blob/8fcec805b5e2248c4146ac1db4fe9fbb61a3b4af/PointOBB/tools_data_trans/test_dota2coco_P2B_obb-pt.py#L48
